"""
Advanced Physiological Artifact and Event Injection Engine.

This module provides the `ArtifactInjector` class, which allows user-defined noise models,
pathologies, or transient spikes to be dynamically injected at specific timestamps.

Physical and Physiological Context:
    During outpatient monitoring, subjects experience discrete movement events (e.g. coughing,
    sensor bumps, muscle contractions). The `ArtifactInjector` models these localized transient
    events rather than continuous noise processes.

Mathematical Formulation:
    For an injection event starting at $t_{\\text{start}}$ and ending at $t_{\\text{end}}$:
    1. Time-Windowing:
       To prevent non-physiological abrupt step discontinuities (spectral splatter), a fading
       window function $w(t)$ is applied. We support a raised-cosine (Tukey) window:
       $$w_{\\text{fade}}(t) = \\begin{cases}
       0.5 \\cdot \\left[ 1 - \\cos\\left(\\pi \\frac{t - t_{\\text{start}}}{\\tau_{\\text{rise}}}\\right) \\right] & \\text{for } t_{\\text{start}} \\le t < t_{\\text{start}} + \\tau_{\\text{rise}} \\\\
       1.0 & \\text{for } t_{\\text{start}} + \\tau_{\\text{rise}} \\le t < t_{\\text{end}} - \\tau_{\\text{fall}} \\\\
       0.5 \\cdot \\left[ 1 - \\cos\\left(\\pi \\frac{t_{\\text{end}} - t}{\\tau_{\\text{fall}}}\\right) \\right] & \\text{for } t_{\\text{end}} - \\tau_{\\text{fall}} \\le t < t_{\\text{end}} \\\\
       0.0 & \\text{otherwise}
       \\end{cases}$$
       where $\\tau_{\\text{rise}}$ and $\\tau_{\\text{fall}}$ are the transition durations in seconds.

    2. Overlap Summation:
       If multiple events overlap in time, their contributions are summed:
       $$x_{\\text{noisy}}(t) = x_{\\text{clean}}(t) + \\sum_{i} w_i(t) \\cdot n_i(t - t_{\\text{start},i})$$
       where $n_i(t)$ is the noise realization generated by model $i$.

    3. Spatial Leakage (Multi-Channel):
       If the target is a multi-channel signal, an injection on channel $c$ can leak to channel $k$
       scaled by a coupling factor $L_{c,k}$:
       $$n_k(t) = L_{c,k} \\cdot n_c(t)$$
"""

from typing import List, Dict, Any, Optional, Tuple, Union
import numpy as np
from biosignal_simulator.core.base import BaseNoiseModel
from biosignal_simulator.core.math_utils import normalize_to_rms

class ArtifactInjector:
    """
    Physiological Event and Artifact Injection Controller.
    
    Manages scheduling, spatial projection, raised-cosine fading windowing,
    and overlapping additions of physiological noise events.
    """
    
    def __init__(self, spatial_coupling: Optional[Union[List[List[float]], np.ndarray]] = None):
        """
        Initialize the Artifact Injector.
        
        Parameters
        ----------
        spatial_coupling : Optional[Union[List[List[float]], np.ndarray]]
            A 2D coupling matrix of shape (n_channels, n_channels) defining how
            injected noise in one channel leaks into adjacent channels. If None,
            leakage is disabled and injections apply only to specified channels.
        """
        self.injections: List[Dict[str, Any]] = []
        self.spatial_coupling = np.array(spatial_coupling) if spatial_coupling is not None else None
        
        if self.spatial_coupling is not None:
            if self.spatial_coupling.ndim != 2 or self.spatial_coupling.shape[0] != self.spatial_coupling.shape[1]:
                raise ValueError("Spatial coupling matrix must be a 2D square matrix.")

    def add(
        self,
        artifact: BaseNoiseModel,
        timestamps_s: Union[List[float], np.ndarray],
        duration_s: float,
        amplitude_scale: float = 1.0,
        target_channels: Optional[List[int]] = None,
        fade_in_s: float = 0.05,
        fade_out_s: float = 0.05,
        jitter_std_s: float = 0.0
    ) -> None:
        """
        Register an artifact model to be injected at specific timestamps.
        
        Parameters
        ----------
        artifact : BaseNoiseModel
            The noise model generator.
        timestamps_s : List[float] or np.ndarray
            Midpoint or start timestamps (seconds) where the artifact events occur.
        duration_s : float
            Total duration of each injected event segment in seconds. Must be > 0.
        amplitude_scale : float
            Scale factor to multiply the noise amplitude. Default is 1.0.
        target_channels : Optional[List[int]]
            Indices of channels to inject the artifact into. If None, injects into all channels.
        fade_in_s : float
            Rise time in seconds for the raised-cosine fade-in transition window.
            Default is 0.05 s.
        fade_out_s : float
            Fall time in seconds for the raised-cosine fade-out transition window.
            Default is 0.05 s.
        jitter_std_s : float
            Standard deviation of random time displacement (seconds) added to each timestamp.
            Default is 0.0 s (no jitter).
        """
        if duration_s <= 0.0:
            raise ValueError("Duration of injected artifact must be positive.")
        if fade_in_s < 0.0 or fade_out_s < 0.0:
            raise ValueError("Fade-in/out times must be non-negative.")
        if fade_in_s + fade_out_s > duration_s:
            raise ValueError("Sum of fade-in and fade-out times cannot exceed total duration.")
        if amplitude_scale < 0.0:
            raise ValueError("amplitude_scale must be non-negative.")
            
        self.injections.append({
            'artifact': artifact,
            'timestamps': np.array(timestamps_s, dtype=float),
            'duration': duration_s,
            'amplitude_scale': amplitude_scale,
            'target_channels': target_channels,
            'fade_in': fade_in_s,
            'fade_out': fade_out_s,
            'jitter_std': jitter_std_s
        })

    def apply(self, clean_signal: np.ndarray, fs: float) -> np.ndarray:
        """
        Inject all registered artifacts into the clean signal, returning the noisy mixture.
        
        Supports 1-D and 2-D multi-channel configurations with overlap and spatial leakage.
        
        Parameters
        ----------
        clean_signal : np.ndarray
            The clean physiological signal (1-D or 2-D).
        fs : float
            Sampling frequency in Hz.
            
        Returns
        -------
        np.ndarray
            The signal corrupted by the injected transient events.
        """
        if len(clean_signal) == 0:
            return np.empty(0, dtype=np.float64)
            
        n_samples = clean_signal.shape[-1]
        t = np.arange(n_samples) / fs
        noisy = clean_signal.copy()
        
        # Check dimensionality
        is_multichannel = clean_signal.ndim == 2
        n_channels = clean_signal.shape[0] if is_multichannel else 1
        
        # We will accumulate injected noise in a separate array to handle overlaps properly
        injected_noise_matrix = np.zeros_like(clean_signal)
        
        for inj in self.injections:
            art = inj['artifact']
            dur = inj['duration']
            amp_scale = inj['amplitude_scale']
            fade_in = inj['fade_in']
            fade_out = inj['fade_out']
            jitter = inj['jitter_std']
            target_ch = inj['target_channels']
            
            n_sub = int(np.round(dur * fs))
            if n_sub <= 0:
                continue
                
            # If no target channels defined, default to all channels
            if target_ch is None:
                target_ch = list(range(n_channels))
                
            # Check for special rate overrides (e.g. ImpulseNoise needs at least 1 spike in dur)
            from biosignal_simulator.noise.impulse import ImpulseNoise
            original_rate = None
            if isinstance(art, ImpulseNoise) and art.config.rate_hz == 0.0:
                original_rate = art.config.rate_hz
                art.config.rate_hz = 1.0 / dur
                
            # B-03 FIX: create jitter RNG once outside the loop \u2014 was re-seeded per iteration
            jitter_rng = np.random.default_rng(art.seed) if jitter > 0.0 else None
            
            # Process each trigger timestamp
            for t_trig in inj['timestamps']:
                # Apply random time jitter
                if jitter > 0.0:
                    t_ev = t_trig + jitter_rng.normal(0.0, jitter)
                else:
                    t_ev = t_trig
                    
                start_idx = int(np.round(t_ev * fs))
                end_idx = min(n_samples, start_idx + n_sub)
                
                if start_idx >= n_samples or end_idx <= 0:
                    continue
                    
                sub_len = end_idx - start_idx
                # Generate base noise segment
                sub_noise = art.generate(sub_len, fs)
                
                # Apply raised-cosine fading window
                t_sub = t[start_idx:end_idx]
                t_rel = t_sub - t_ev
                window = self._compute_tukey_window(t_rel, dur, fade_in, fade_out)
                sub_noise_windowed = sub_noise * window * amp_scale
                
                # Apply to target channels
                if is_multichannel:
                    for ch in target_ch:
                        injected_noise_matrix[ch, start_idx:end_idx] += sub_noise_windowed
                else:
                    injected_noise_matrix[start_idx:end_idx] += sub_noise_windowed
                    
            # Restore overridden rate
            if original_rate is not None:
                art.config.rate_hz = original_rate

        # --- Apply Spatial Coupling Leakage ---
        if is_multichannel and self.spatial_coupling is not None:
            if self.spatial_coupling.shape[0] != n_channels:
                raise ValueError(
                    f"Spatial coupling dimensions {self.spatial_coupling.shape} "
                    f"must match signal channels ({n_channels})."
                )
            # Mix the injected noise using the spatial leakage matrix
            leaked_noise = np.dot(self.spatial_coupling, injected_noise_matrix)
            noisy += leaked_noise
        else:
            noisy += injected_noise_matrix
            
        return noisy

    def _compute_tukey_window(self, t_rel: np.ndarray, duration: float, rise_t: float, fall_t: float) -> np.ndarray:
        """Compute a raised-cosine fade-in/fade-out Tukey window."""
        window = np.ones_like(t_rel)
        
        # Fade-in raised cosine
        if rise_t > 0.0:
            mask_rise = t_rel < rise_t
            window[mask_rise] = 0.5 * (1.0 - np.cos(np.pi * t_rel[mask_rise] / rise_t))
            
        # Fade-out raised cosine
        if fall_t > 0.0:
            t_end = duration
            mask_fall = t_rel >= (t_end - fall_t)
            window[mask_fall] = 0.5 * (1.0 - np.cos(np.pi * (t_end - t_rel[mask_fall]) / fall_t))
            
        # Out of bounds safety
        window[t_rel < 0.0] = 0.0
        window[t_rel > duration] = 0.0
        
        return window
