"""
Electromyographic (EMG) Muscle Activity Artifact Contamination Simulator.

This module provides the `EMGArtifact` class, which models the high-frequency electrical
interference generated by muscle contractions that pollutes other biopotential recordings
(such as ECG, EEG, and sleep studies).

Physiological and Physical Context:
    EMG artifacts are caused by voluntary or involuntary contractions of muscles close to the
    recording electrodes (e.g. pectoral muscles for ECG, temporalis/masseter muscles for EEG).
    1. Spectral characteristics: Wideband high-frequency noise distributed between 20 Hz and
       500 Hz, with a peak frequency around 60-150 Hz.
    2. Temporal characteristics: Occurs as continuous background muscle tension (tonic activity)
       or sudden, high-amplitude bursts (phasic activity) due to subject movement, speech,
       swallowing, or shivering.
    3. Muscle Fatigue (Spectral Compression): During sustained contractions, metabolic changes in
       muscle fibers lead to a decrease in action potential conduction velocity. Mathematically,
       this manifests as a progressive spectral shift towards lower frequencies (median frequency compression).

Mathematical Formulation:
    The EMG artifact signal $EMG(t)$ is modeled as a product of a bandpass filtered noise process
    $N_{\\text{emg}}(t)$ and an activity envelope $A_{\\text{env}}(t)$, with optional time-varying spectral shift:
    $$EMG(t) = \\gamma \\cdot N_{\\text{emg}}(t, t_{\\text{fatigue}}) \\cdot A_{\\text{env}}(t)$$

    where:
    1. Activity Envelope $A_{\\text{env}}(t)$:
       Sum of continuous background tonic tension $A_{\\text{tonic}}$ and Poisson-distributed phasic activation bursts:
       $$A_{\\text{env}}(t) = A_{\\text{tonic}} + \\sum_{i} e^{-\\frac{(t - \\tau_i)^2}{2\\sigma^2}}$$
       where $\\tau_i$ are Poisson burst times, and $\\sigma$ is the burst duration standard deviation.

    2. Time-Varying Fatigue Filter $N_{\\text{emg}}(t, t_{\\text{fatigue}})$:
       Raw Gaussian noise is passed through a bandpass filter $[f_{\\text{low}}(t), f_{\\text{high}}(t)]$ where
       the cutoff frequencies shrink exponentially over time to model fatigue:
       $$f_{\\text{low}}(t) = f_{\\text{low},0} \\cdot e^{-\\eta t}, \\quad f_{\\text{high}}(t) = f_{\\text{high},0} \\cdot e^{-\\eta t}$$
       where $\\eta$ is the fatigue rate parameter.
"""

from typing import Optional, Union, List, Tuple
import numpy as np
from scipy import signal as sp_signal
from biosignal_simulator.noise.base import BaseNoiseModel
from biosignal_simulator.core.config import EMGArtifactConfig
from biosignal_simulator.core.math_utils import normalize_to_rms
from biosignal_simulator.utils.validation import validate_config

class EMGArtifact(BaseNoiseModel):
    """
    EMG Muscle Contamination Artifact Simulator.
    
    Synthesizes wideband muscle pollution using Poisson-distributed phasic bursts,
    continuous tonic baseline muscle tension, and dynamic muscle fatigue spectral compression.
    """
    
    def __init__(
        self,
        config: Optional[EMGArtifactConfig] = None,
        tonic_amplitude: float = 0.05,
        fatigue_rate: float = 0.0,
        **kwargs
    ):
        """
        Initialize the EMG Artifact model.
        
        Parameters
        ----------
        config : Optional[EMGArtifactConfig]
            Base configuration specifying bandpass frequencies, burst rates, and amplitude fractions.
        tonic_amplitude : float
            Amplitude of continuous background muscle tension (tonic activity). Default is 0.05.
        fatigue_rate : float
            Spectral compression rate representing muscle fatigue.
            If > 0, the frequency spectrum of the EMG artifact shifts lower over time.
            Default is 0.0 (no fatigue).
        **kwargs :
            Alternative parameters passed to EMGArtifactConfig if config is None.
        """
        if config is None:
            config = EMGArtifactConfig(**kwargs)
        else:
            validate_config(config)
            
        super().__init__(seed=config.seed)
        self.config = config
        self.tonic_amplitude = tonic_amplitude
        self.fatigue_rate = fatigue_rate

    def generate(self, n_samples: int, fs: float) -> np.ndarray:
        """
        Synthesize raw 1-D EMG artifact.
        
        Parameters
        ----------
        n_samples : int
            Number of samples.
        fs : float
            Sampling frequency in Hz.
            
        Returns
        -------
        np.ndarray
            1-D noise array of shape (n_samples,).
        """
        if n_samples <= 0:
            return np.empty(0, dtype=np.float64)
            
        t = np.arange(n_samples) / fs
        dur = n_samples / fs
        nyq = 0.5 * fs

        # --- 1. Compute Activity Envelope (Tonic + Phasic Bursts) ---
        envelope = np.ones(n_samples) * self.tonic_amplitude
        lam = self.config.burst_rate_hz
        
        if lam > 0:
            # Draw phasic burst times using Poisson process
            num_events = self.rng.poisson(lam=lam * dur)
            if num_events > 0:
                event_times = self.rng.uniform(0.0, dur, size=num_events)
                b_dur = self.config.burst_duration_s
                sigma = max(1e-5, b_dur / 4.0)
                
                for t_ev in event_times:
                    # Gaussian burst envelope shape
                    envelope += np.exp(-0.5 * ((t - t_ev) / sigma) ** 2)

        # --- 2. Filter Raw Noise with Dynamic Fatigue Spectral Compression ---
        raw_noise = self.rng.normal(0.0, 1.0, size=n_samples)
        
        f_low_init = max(0.1, self.config.fmin_hz)
        f_high_init = min(self.config.fmax_hz, nyq - 0.1)
        
        if self.fatigue_rate > 0.0:
            # Time-varying filter simulation for muscle fatigue
            # We partition the signal into small sliding blocks to apply different filter cutoffs
            block_size = int(np.round(0.5 * fs))  # 500 ms blocks
            if block_size < 10:
                block_size = n_samples
                
            filtered_noise = np.zeros(n_samples)
            num_blocks = int(np.ceil(n_samples / block_size))
            
            for b_idx in range(num_blocks):
                start = b_idx * block_size
                end = min(n_samples, (b_idx + 1) * block_size)
                if start >= end:
                    break
                    
                t_block = start / fs
                # Compress cutoffs exponentially over time
                decay_factor = np.exp(-self.fatigue_rate * t_block)
                f_low = max(0.1, f_low_init * decay_factor)
                f_high = max(f_low + 5.0, f_high_init * decay_factor)
                
                # Prevent cutoffs from escaping Nyquist boundaries
                f_low = min(f_low, nyq - 10.0)
                f_high = min(f_high, nyq - 5.0)
                
                block_raw = raw_noise[start:end]
                if len(block_raw) > 5 and f_low < f_high:
                    b_f, a_f = sp_signal.butter(4, [f_low / nyq, f_high / nyq], btype='bandpass')
                    # Zero-phase filtering requires padding. If block is short, use simple lfilter
                    pad_len = min(150, len(block_raw) // 3)
                    if pad_len > 5:
                        filtered_noise[start:end] = sp_signal.filtfilt(b_f, a_f, block_raw, padlen=pad_len)
                    else:
                        filtered_noise[start:end] = sp_signal.lfilter(b_f, a_f, block_raw)
                else:
                    filtered_noise[start:end] = block_raw
        else:
            # Stationary bandpass filtering
            if f_low_init < f_high_init:
                b_f, a_f = sp_signal.butter(4, [f_low_init / nyq, f_high_init / nyq], btype='bandpass')
                filtered_noise = sp_signal.filtfilt(b_f, a_f, raw_noise)
            else:
                filtered_noise = raw_noise
                
        # Normalize filtered signal to unit RMS
        filtered_noise = normalize_to_rms(filtered_noise, 1.0)
        
        # Combine bandpass noise and envelopes
        emg_noise = filtered_noise * envelope
        
        # Scale to requested amplitude fraction
        return normalize_to_rms(emg_noise, self.config.amplitude_fraction)

    def generate_multichannel(self, n_channels: int, n_samples: int, fs: float) -> np.ndarray:
        """
        Synthesize multi-channel EMG artifacts with optional leakage cross-coupling.
        
        Models how a single muscular source (e.g. chest wall) couples into multiple
        neighboring lead channels.
        
        Parameters
        ----------
        n_channels : int
            Number of channels.
        n_samples : int
            Number of samples.
        fs : float
            Sampling frequency in Hz.
            
        Returns
        -------
        np.ndarray
            2-D noise array of shape (n_channels, n_samples).
        """
        if n_channels <= 0 or n_samples <= 0:
            return np.empty((n_channels, 0), dtype=np.float64)
            
        # Generate independent EMG sources representing different muscles
        # Mix them slightly (20% coupling) to model spatial leakage
        raw_emg_channels = np.zeros((n_channels, n_samples))
        for c in range(n_channels):
            raw_emg_channels[c] = self.generate(n_samples, fs)
            
        mixed_emg = np.zeros((n_channels, n_samples))
        for c in range(n_channels):
            # Mix 80% own channel + 20% average of other channels
            other_avg = np.zeros(n_samples)
            if n_channels > 1:
                other_avg = (np.sum(raw_emg_channels, axis=0) - raw_emg_channels[c]) / (n_channels - 1)
            mixed_emg[c] = 0.8 * raw_emg_channels[c] + 0.2 * other_avg
            # Restore target amplitude scale
            mixed_emg[c] = normalize_to_rms(mixed_emg[c], self.config.amplitude_fraction)
            
        return mixed_emg
